## Pytorch

### Basics

In [2]:
import torch
import numpy as np

In [3]:
SEED = 12
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

In [6]:
x = torch.randn(2,3)
x.shape

torch.Size([2, 3])

In [7]:
x = torch.zeros(2)
n = np.zeros(2)
x, n

(tensor([0., 0.]), array([0., 0.]))

In [8]:
torch.tensor([[1,2,3], [3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [9]:
torch.tensor(np.random.rand(2,3))

tensor([[0.1542, 0.7400, 0.2633],
        [0.5337, 0.0146, 0.9187]], dtype=torch.float64)

In [10]:
x = torch.randn(2,3)
y = torch.randn(2,3)
x+y

tensor([[ 2.6127,  1.2648, -0.5284],
        [-2.7385,  0.5901, -0.1000]])

In [11]:
x = torch.randn(2,3)
y = torch.randn(3,2)
torch.mm(x,y)

tensor([[ 0.8424,  0.6460],
        [-1.0042, -2.9688]])

In [19]:
x.mm(y)

tensor([[ 0.8424,  0.6460],
        [-1.0042, -2.9688]])

In [15]:
x.numpy().dot(y.numpy())

array([[ 0.84235907,  0.6460462 ],
       [-1.0041898 , -2.9687512 ]], dtype=float32)

In [17]:
x.t()

tensor([[ 1.1042,  0.2536],
        [ 0.5371,  0.1490],
        [-0.4682,  2.1302]])

In [25]:
x, x.reshape(1,6), x.view(1,6)

(tensor([[ 1.1042,  0.5371, -0.4682],
         [ 0.2536,  0.1490,  2.1302]]),
 tensor([[ 1.1042,  0.5371, -0.4682,  0.2536,  0.1490,  2.1302]]),
 tensor([[ 1.1042,  0.5371, -0.4682,  0.2536,  0.1490,  2.1302]]))

In [30]:
x, x.sum(axis=0), x.sum(axis=1)

(tensor([[ 1.1042,  0.5371, -0.4682],
         [ 0.2536,  0.1490,  2.1302]]),
 tensor([1.3579, 0.6861, 1.6620]),
 tensor([1.1731, 2.5329]))

In [ ]:
x, x[:1, 1:3]

(tensor([[ 1.1042,  0.5371, -0.4682],
         [ 0.2536,  0.1490,  2.1302]]),
 tensor([[ 0.5371, -0.4682]]))

In [38]:
torch.cat((x,x)).shape

torch.Size([4, 3])

In [39]:
torch.stack((x,x)).shape

torch.Size([2, 2, 3])

In [40]:
x = torch.rand(3, 4, requires_grad=True)

In [44]:
y = 3 * x + 2

In [45]:
z = y.mean()

In [47]:
z.backward()

In [49]:
x.grad

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

In [53]:
torch.cuda.is_available()

False

### Pre-trained models from torch hub

In [76]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision.datasets import CIFAR10
from torchvision.transforms import ToTensor

In [ ]:
dataset = CIFAR10(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

In [78]:
train_dataloader = DataLoader(dataset, batch_size=64, shuffle=True)

In [55]:
num_classes = 10

Using cache found in /Users/arthur/.cache/torch/hub/pytorch_vision_v0.10.0
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /Users/arthur/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100.0%


In [71]:
model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet50', pretrained=True)
model.fc = torch.nn.Linear(in_features=2048, out_features=num_classes, bias=True)

In [80]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [82]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

In [ ]:
epochs = 1
for epoch in range(epochs):
    for batch_id, (inputs, labels) in enumerate(train_dataloader):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

In [98]:
from typing import List, Dict
from pydantic import BaseModel, validator
from enum import Enum


class UnitType(Enum):
    SUBJECT = "subject"
    TOPIC = "topic"
    CONCEPT = "concept"


class AllUnitTypes(BaseModel):
    units: List[UnitType]

    class Config:
        arbitrary_types_allowed = True


In [101]:
test = AllUnitTypes(units=["subject", "topic", "concept"])

In [109]:
[unit_type.value for unit_type in test.units]

['subject', 'topic', 'concept']